---
title: "Sentiment Analysis of Tweets regarding ChatGPT"
execute:
    echo: true
---


```{r setup}
library(tidyverse)
library(tidytext)
library(ggplot2)
install.packages("textstem")
library(textstem)
```


## Load Data
```{r load-data}
data <- read_csv("file.csv")
head(data)
```


## Clean and Tokenize Text
```{r tokenize}
# Remove stopwords and lemmatize
stop_words <- tidytext::stop_words

tidy_data <- data |>
    unnest_tokens(word, tweet_txt) |> # unnest_tokens automatically converts tokens to lowercase by default
    anti_join(stop_words, by = "word") |>
    mutate(word = lemmatize_words(word))
```


## Sentiment Summary (Provided Labels)
```{r sentiment-summary}
data |>
    count(label_txt)
```


## Word Frequencies by Sentiment
```{r word-freq}
word_counts <- tidy_data |>
    count(label_txt, word, sort = TRUE)
head(word_counts)
```


## Plot Word Frequencies
```{r plot}
word_counts |>
    filter(n > 5) |>
    ggplot(aes(x = n, y = reorder(word, n), fill = label_txt)) +
        geom_col() +
        labs(title = "Word Frequency by Sentiment", x = "Count", y = "Word")
```

## Identify predominantly positive (good) and negative (bad) words

```{r tfidf}
tfidf_data <- tidy_data |>
    count(label_txt, word) |>
    bind_tf_idf(word, label_txt, n)


positive_words <- tfidf_data |>
    filter(label_txt == "good") |>
    arrange(desc(tf_idf)) |>
    slice_max(tf_idf, n = 25)


negative_words <- tfidf_data |>
    filter(label_txt == "bad") |>
    arrange(desc(tf_idf)) |>
    slice_max(tf_idf, n = 25)
```

## Plot Top Positive Words
```{r plot-positive}
positive_words |>
    ggplot(aes(x = tf_idf, y = reorder(word, tf_idf))) +
        geom_col(fill = "steelblue") +
        labs(title = "Top 25 TF-IDF Weighted Positive Words", x = "TF-IDF Weight", y = "Word")
```


## Plot Top Negative Words
```{r plot-negative}
negative_words |>
    ggplot(aes(x = tf_idf, y = reorder(word, tf_idf))) +
        geom_col(fill = "firebrick") +
        labs(title = "Top 25 TF-IDF Weighted Negative Words", x = "TF-IDF Weight", y = "Word")
```
